name: Build and Release .NET 8 Application

on:
  push:
    branches:
      - master  # Verwende master branch
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Beachte, dass dieser Job unter Windows läuft

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet publish -c Release -r win-x64 --self-contained -o ./output

    - name: Archive binaries
      run: |
        mkdir -p dist
        cp ./output/* dist/
      
    - name: List files in dist (build job)
      run: |
        echo "Listing files in dist/ directory after build:"
        Get-ChildItem -Path dist

    - name: Upload binaries as artifact
      uses: actions/upload-artifact@v3
      with:
        name: winx64-binaries
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest  # Alternativ kann auch 'windows-latest' genutzt werden

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: winx64-binaries
        path: ./dist/  # Lade das Artefakt in das `dist` Verzeichnis herunter

    - name: List files in dist (release job)
      run: |
        echo "Listing files in dist/ directory after download:"
        ls -al dist/

    - name: Create ZIP archive
      run: |
        zip -r deovrScraper.zip ./dist/*

    - name: Set up GitHub CLI
      run: sudo apt-get install -y gh

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Verwende PAT_TOKEN statt des standardmäßigen GITHUB_TOKEN
      run: |
        echo "Creating GitHub release..."
        gh release create ${{ github.ref_name }} deovrScraper.zip --title "Release ${{ github.ref_name }}" --notes "Automated release for ${{ github.ref_name }}"
