name: Build, Tag, and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Determine next version
      id: vars
      run: |
        echo "Determining the latest tag..."
        LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "v0.0.0")
        echo "Latest tag: $LATEST_TAG"
        
        if [ "$LATEST_TAG" = "v0.0.0" ]; then
          NEXT_VERSION="v1.0.0"
        else
          VERSION_PARTS=(${LATEST_TAG//v/ })
          VERSION_PARTS=(${VERSION_PARTS//./ })
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}

          PATCH=$((PATCH + 1))
          NEXT_VERSION="v$MAJOR.$MINOR.$PATCH"
        fi

        echo "Determined next version: $NEXT_VERSION"
        echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

    - name: Determine architecture
      id: arch
      run: |
        echo "Determining architecture..."
        ARCHITECTURE=$(uname -m)
        echo "Architecture: $ARCHITECTURE"
        echo "ARCHITECTURE=$ARCHITECTURE" >> $GITHUB_ENV

    - name: Create Tag using GitHub API via curl
      run: |
        echo "Creating tag ${{ env.NEXT_VERSION }}..."
        TAG_RESPONSE=$(curl -X POST -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
        -d '{"ref":"refs/tags/${{ env.NEXT_VERSION }}","sha":"${{ github.sha }}"}' \
        https://api.github.com/repos/${{ github.repository }}/git/refs 2>&1)
        echo "Tag creation response: $TAG_RESPONSE"

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: |
        echo "Restoring dependencies..."
        dotnet restore

    - name: Build the project
      run: |
        echo "Building the project..."
        dotnet publish -c Release -r win-x64 --self-contained -o ./output

    - name: Archive binaries
      run: |
        echo "Archiving binaries..."
        mkdir -p dist
        cp -r ./output/* dist/
        echo "Files in dist after copying:"
        ls -al dist/

    - name: List files in dist (build job)
      run: |
        echo "Listing files in dist/ directory after build:"
        ls -al dist/

    - name: Upload binaries as artifact
      uses: actions/upload-artifact@v3
      with:
        name: winx64-binaries
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: winx64-binaries
        path: ./dist/

    - name: List files in dist (release job)
      run: |
        echo "Listing files in dist/ directory after download:"
        ls -al dist/

    - name: Create ZIP archive
      run: |
        echo "Creating ZIP archive..."
        ZIP_NAME="release_${{ env.NEXT_VERSION }}_${{ env.ARCHITECTURE }}.zip"
        echo "ZIP_NAME=$ZIP_NAME"
        zip -r $ZIP_NAME ./dist/*
        echo "Created ZIP file:"
        ls -al $ZIP_NAME
        echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

    - name: Verify ZIP archive creation
      run: |
        if [ -f "${{ env.ZIP_NAME }}" ]; then
          echo "ZIP archive successfully created."
        else
          echo "Error: ZIP archive was not created."
          exit 1
        fi

    - name: Set up GitHub CLI
      run: |
        echo "Installing GitHub CLI..."
        sudo apt-get install -y gh

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        echo "Creating GitHub release..."
        echo "Attempting to release ${{ env.ZIP_NAME }} with title 'Release ${{ env.NEXT_VERSION }}'"
        RELEASE_RESPONSE=$(gh release create ${{ env.NEXT_VERSION }} ${{ env.ZIP_NAME }} --title "Release ${{ env.NEXT_VERSION }}" --notes "Automated release for version ${{ env.NEXT_VERSION }}" 2>&1)
        echo "Release creation response: $RELEASE_RESPONSE"
        if echo "$RELEASE_RESPONSE" | grep -q "HTTP 422"; then
          echo "Error: Release creation failed due to an existing tag or other issue."
          exit 1
        fi
